### ISSUE TITLE
ch13_13.15_3.hs

### ISSUE THREAD

**Issue by svozza** [lukleh/haskell-book-exercises#10]
Hi there,
First of all a big thank you for posting your solutions, it's great to be able to compare mine with other's who've worked through the material. In the solution for the above exercise I noticed this comment:

```
not sure I get the assignment other than using toLower
```

Another thing that can be done to get palindromes regardless of punctuation is to use the `isLetter` function from `Data.Char`. I can raise a PR if you want...

**Comment by lukleh** [comment]
Hi :)

PR would be great.

**Comment by svozza** [comment]
No probs! :)
