### ISSUE TITLE
11.9 Product types

### ISSUE THREAD

**Issue by e19293001** [lukleh/haskell-book-exercises#2]
sortJams in no. 9 doesn't seem to work.

Here is my solution:
```
module Jammin where

import Data.List

data Fruit =
  Peach
  | Plum
  | Apple
  | Blackberry
  deriving (Eq, Show, Ord)

data JamJars = Jam { fruit :: Fruit,
                numjars :: Int }
             deriving (Eq, Show, Ord)

row1 = Jam Peach 10
row2 = Jam Plum 30
row3 = Jam Apple 20
row4 = Jam Blackberry 4
row5 = Jam Peach 34
row6 = Jam Apple 50

allJam = [row1, row2, row3, row4, row5, row6]

-- Solution to 9.
sortJams :: [JamJars] -> [JamJars]
sortJams = sortBy (\x y -> compare (numjars x) (numjars y))
```

**Comment by lukleh** [comment]
In the book they actually want to compare based on the kind of fruit. 
![image](https://cloud.githubusercontent.com/assets/148259/18219037/50f3426a-716f-11e6-950a-cf33bf88bd59.png)
You are comparing it based on the count, which sounds a little big more logical, but then it does not work with the `groupJam` function in the next step.

**Comment by e19293001** [comment]
This is my mistake. sortJams in no. 9 works correctly.
