### ISSUE TITLE
Take these down please

### ISSUE THREAD

**Issue by bitemyapp** [lukleh/haskell-book-exercises#21]
Hi, I'm a coauthor of Haskell Programming from First Principles!

We don't want the answers available online. Also, the exercises are a big part of what makes the book valuable and they're our copyright. Please take this repository down. I hate to do this as you clearly put a lot of effort into organizing the content but you should ask the authors in future before reproducing their work elsewhere.

**Comment by lukleh** [comment]
Hi Chris,

I will take the repo down as you wish. 

My personal opinion is that this claim is a little bit far fetched  (I do not know about anything similar) and I know you know about this repo for already quite some time (you retweeted when I was announcing it).

Anyway, I would appriciate to talk more about it to make a closure.

Ping me
