### ISSUE TITLE
ch04_4.2_0 fix

### ISSUE THREAD

**Issue by madhukar93** [lukleh/haskell-book-exercises#3]
The function `changeMood` is supposed to flip the mood. The provided solution would just return `Blah` for any input.

This is what I believe that the function should be
```
data Mood = Blah | Woot deriving Show
changeMood :: Mood -> Mood
changeMood Blah = Woot
changeMood Woot = Blah
```

**Comment by lukleh** [comment]
hi @madhukar93 
```
changeMood Blah = Woot
changeMood _ = Blah
```
and
```
changeMood Blah = Woot
changeMood Woot = Blah
```
are in this case identical, `changeMood _ = Blah` is reached only for `Woot`, so it is the same as `changeMood Woot = Blah`

did you try to test my version?

**Comment by madhukar93** [comment]
This is what I got
> Prelude> let changeMood Blah = Woot
Prelude> let changeMood _ = Blah
Prelude> changeMood Blah
Blah

Doesn't `changeMood _ = Blah` mean that any argument (of type mood) evaluates to `Blah`. When in fact the function is supposed to change the mood.

**Comment by lukleh** [comment]
@madhukar93 sure, great you figured it out! keep going over the code ;)
